@startuml Persons_scenario6_state1_001_initial

<style>
    Shadowing false
    Rectangle {
        FontSize 18
        FontStyle bold
        HorizontalAlignment left
        LineThickness 0
        RoundCorner 20
    }
    Object {
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor white
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>

title \
<b>Sequence:</b> Persons\n\
<b>Scenario:</b> scenario6 - Anton, Berta, and Charlie become friends and get older. Then the situation changes again.\n\
<b>Transition State:</b> state1 - The first transition state. Let's add some more text to force line breaks in diagrams.\n\n\
<b>Initial setup</b>\n\n\
Diagram 001 of 009

rectangle "The Person Domain" as persondomain #DDDDDD {
    rectangle "Person-to-Person Relation" as persondomain_p2pclass #white {
        object "<color:white><b>p2p01</b></color>" as persondomain_p2pclass_p2p01 #white {
            <color:white>person_fk = "(anton, berta)"</color>
            <color:white>type = "marriage"</color>
        }
        object "<color:white><b>p2p02</b></color>" as persondomain_p2pclass_p2p02 #white {
            <color:white>person_fk = "(anton, berta, charlie)"</color>
            <color:white>type = "friendship"</color>
        }
    }
    rectangle "Person" as persondomain_personclass #white {
        object "<color:white><b>anton</b></color>" as persondomain_personclass_anton #white {
            <color:white>age = "23"</color>
            <color:white>name = "Anton A"</color>
        }
        object "<color:white><b>berta</b></color>" as persondomain_personclass_berta #white {
            <color:white>age = "34"</color>
            <color:white>name = "Berta B"</color>
        }
        object "<color:white><b>charlie</b></color>" as persondomain_personclass_charlie #white {
            <color:white>age = "45"</color>
            <color:white>name = "Charlie C"</color>
        }
    }
}

persondomain_p2pclass_p2p01 --[hidden]--> persondomain_personclass_anton
persondomain_p2pclass_p2p01 --[hidden]--> persondomain_personclass_berta
persondomain_p2pclass_p2p02 --[hidden]--> persondomain_personclass_anton
persondomain_p2pclass_p2p02 --[hidden]--> persondomain_personclass_berta
persondomain_p2pclass_p2p02 --[hidden]--> persondomain_personclass_charlie

@enduml
