@startuml PersonsAndHouses_scenario4_state1_002_event0401_001

<style>
    Shadowing false
    Rectangle {
        FontSize 18
        FontStyle bold
        HorizontalAlignment left
        LineThickness 0
        RoundCorner 20
    }
    Object {
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor white
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>

title \
<b>Sequence:</b> PersonsAndHouses\n\
<b>Scenario:</b> scenario4 - Charlie moves in to the first house, second floor.\n\
<b>Transition State:</b> state1 - The first transition state. Let's add some more text to force line breaks in diagrams.\n\n\
<b>Business Event:</b> event0401 - Charlie spawns on earth. (Step 001 of 001)\n\n\
Diagram 002 of 004

rectangle "The House Domain" as housedomain #DDDDDD {
    rectangle "Floor" as housedomain_floorclass #white {
        object "<color:white><b>floor0102</b></color>" as housedomain_floorclass_floor0102 #white {
            <color:white>house_fk = "house01"</color>
            <color:white>name = "The Second Floor"</color>
        }
    }
}
rectangle "The Person Domain" as persondomain #DDDDDD {
    rectangle "Person-to-Floor Relation" as persondomain_p2fclass #white {
        object "<color:white><b>p2f05</b></color>" as persondomain_p2fclass_p2f05 #white {
            <color:white>floor_fk = "floor0102"</color>
            <color:white>person_fk = "charlie"</color>
            <color:white>type = "tenant"</color>
        }
    }
    rectangle "Person" as persondomain_personclass #white {
        object "<color:black><b>charlie</b></color>" as persondomain_personclass_charlie #palegreen {
            <color:black>age = "45"</color>
            <color:black>name = "Charlie C"</color>
        }
    }
}

persondomain_p2fclass_p2f05 --[hidden]--> housedomain_floorclass_floor0102
persondomain_p2fclass_p2f05 --[hidden]--> persondomain_personclass_charlie

@enduml
