@startuml PersonsAndHouses_scenario4_state1_004_final

<style>
    Shadowing false
    Rectangle {
        FontSize 18
        FontStyle bold
        HorizontalAlignment left
        LineThickness 0
        RoundCorner 20
    }
    Object {
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor white
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle normal
        HorizontalAlignment left
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>

title \
<b>Sequence:</b> PersonsAndHouses\n\
<b>Scenario:</b> scenario4 - Charlie moves in to the first house, second floor.\n\
<b>Transition State:</b> state1 - The first transition state. Let's add some more text to force line breaks in diagrams.\n\n\
<b>Final object model</b>\n\n\
Diagram 004 of 004

rectangle "The House Domain" as housedomain #DDDDDD {
    rectangle "Floor" as housedomain_floorclass #white {
        object "<color:black><b>floor0102</b></color>" as housedomain_floorclass_floor0102 #EEEEEE {
            <color:black>house_fk = "house01"</color>
            <color:black>name = "The Second Floor"</color>
        }
    }
}
rectangle "The Person Domain" as persondomain #DDDDDD {
    rectangle "Person-to-Floor Relation" as persondomain_p2fclass #white {
        object "<color:black><b>p2f05</b></color>" as persondomain_p2fclass_p2f05 #DDFFCC {
            <color:black>floor_fk = "floor0102"</color>
            <color:black>person_fk = "charlie"</color>
            <color:black>type = "tenant"</color>
        }
    }
    rectangle "Person" as persondomain_personclass #white {
        object "<color:black><b>charlie</b></color>" as persondomain_personclass_charlie #DDFFCC {
            <color:black>age = "45"</color>
            <color:black>name = "Charlie C"</color>
        }
    }
}

persondomain_p2fclass_p2f05 ----> housedomain_floorclass_floor0102 #555555
persondomain_p2fclass_p2f05 ----> persondomain_personclass_charlie #555555

@enduml
