@startuml scenarios

<style>
    Shadowing false
    Rectangle {
        BackgroundColor cornsilk
        FontSize 18
        FontStyle normal
        HorizontalAlignment left
        LineColor black
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineColor black
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle bold
        HorizontalAlignment center
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>


title Scenarios and their predecessors

rectangle "<b>scenario1</b>\n\nThe first house is built, and\nthen Anton moves in to the\nfirst floor." as scenario1
rectangle "<b>scenario2</b>\n\nAnton marries Berta, and Berta\nmoves into the first house to\nthe first floor as well." as scenario2
rectangle "<b>scenario3</b>\n\nThe second house is built, and\nAnton and Berta move from\nfirst house to second house,\nthird floor." as scenario3
rectangle "<b>scenario4</b>\n\nCharlie moves in to the first\nhouse, second floor." as scenario4
rectangle "<b>scenario5</b>\n\nThe first house is destroyed,\nbut before that, Charlie\nluckily also moves to the\nsecond house, fourth floor,\nbut kept tenant contract with\nfirst house." as scenario5

scenario2 ---> scenario1
scenario3 ---> scenario2
scenario4 ---> scenario1
scenario5 ---> scenario1
scenario5 ---> scenario4

@enduml
