@startuml transitionstates

<style>
    Shadowing false
    Rectangle {
        BackgroundColor cornsilk
        FontSize 18
        FontStyle normal
        HorizontalAlignment left
        LineColor black
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineColor black
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle bold
        HorizontalAlignment center
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>


title Transition states and their predecessors

rectangle "<b>state1</b>\n\nThis is transition state 1." as state1
rectangle "<b>state2</b>\n\nThis is transition state 2.\nOne two three four five six\nseven eight nine ten." as state2
rectangle "<b>state3</b>\n\nThis is transition state 3.\nOne two three four five six\nseven eight nine ten. One two\nthree four five six seven\neight nine ten." as state3
rectangle "<b>state4</b>\n\nThis is transition state 4.\nOne two three four five six\nseven eight nine ten. One two\nthree four five six seven\neight nine ten. One two three\nfour five six seven eight nine\nten." as state4
rectangle "<b>state5</b>\n\nThis is transition state 5." as state5

state2 ---> state1
state3 ---> state2
state4 ---> state3

@enduml
