@startuml transitionstates

top to bottom direction
skinparam shadowing false
skinparam componentStyle uml2
skinparam roundCorner 10

skinparam rectangleRoundCorner 20
skinparam rectangleFontStyle normal
skinparam rectangleFontSize 18
skinparam rectangleBorderColor #black
skinparam rectangleBorderThickness 3
skinparam rectangleBackgroundColor #cornsilk

skinparam arrowColor #black
skinparam arrowFontSize 18
skinparam arrowThickness 3

skinparam titleFontSize 22
skinparam titleFontStyle bold


title \nTransition states and their predecessors\n

rectangle "<b>state1</b>\n\nThis is transition state 1." as state1
rectangle "<b>state2</b>\n\nThis is transition state 2.\nOne two three four five six\nseven eight nine ten." as state2
rectangle "<b>state3</b>\n\nThis is transition state 3.\nOne two three four five six\nseven eight nine ten. One two\nthree four five six seven\neight nine ten." as state3
rectangle "<b>state4</b>\n\nThis is transition state 4.\nOne two three four five six\nseven eight nine ten. One two\nthree four five six seven\neight nine ten. One two three\nfour five six seven eight nine\nten." as state4
rectangle "<b>state5</b>\n\nThis is transition state 5." as state5

state2 ---> state1
state3 ---> state2
state4 ---> state3

@enduml
