@startuml transitionstates

<style>
    Shadowing false
    Rectangle {
        BackgroundColor cornsilk
        FontSize 18
        FontStyle normal
        HorizontalAlignment left
        LineColor black
        LineThickness 3
        RoundCorner 20
    }
    Arrow {
        LineColor black
        LineThickness 3
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle bold
        HorizontalAlignment center
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>


title Transition states and their predecessors

rectangle "<b>state1</b>\n\nThe first transition state.\nLet's add some more text to\nforce line breaks in diagrams." as state1
rectangle "<b>state2</b>\n\nThe second transition state.\nHere some more text." as state2
rectangle "<b>state3</b>\n\nThe third transition state.\nAnd here is some another text." as state3

state2 ---> state1
state3 ---> state1

@enduml
