@startmindmap businessevents

<style>
    Shadowing false
    RootNode {
        BackgroundColor #EEEEEE
        FontSize 16
        FontStyle bold
        Padding 20
        Margin 20
        HorizontalAlignment left
        RoundCorner 20
        MaximumWidth 200
        LineColor black
        LineThickness 3
    }
    LeafNode {
        BackgroundColor cornsilk
        FontSize 16
        FontStyle normal
        Padding 20
        Margin 20
        HorizontalAlignment left
        LineColor black
        LineThickness 3
        RoundCorner 20
        MaximumWidth 300
    }
    Arrow {
        LineStyle 5
        LineThickness 3
        LineColor black
    }
    Title {
        BackgroundColor white
        FontColor darkblue
        FontSize 20
        FontStyle bold
        HorizontalAlignment center
        LineColor darkblue
        LineThickness 2
        Margin 50
        Padding 20
    }
</style>


title Business events and the scenarios they belong to

* scenario1
** <b>event0101</b>\n\nThe first house is built with in total two floors.
** <b>event0102</b>\n\nAnton spawns on earth.
** <b>event0103</b>\n\nAnton moves in to first house, first floor.
* scenario2
** <b>event0201</b>\n\nBerta spawns on earth.
** <b>event0202</b>\n\nAnton and Berta marry each other.
** <b>event0203</b>\n\nBerta moves in to first house, first floor, as well.
* scenario3
** <b>event0301</b>\n\nThe second house is built with in total four floors.
** <b>event0302</b>\n\nAnton and Berta move from first house to second house, third floor.
* scenario4
** <b>event0401</b>\n\nCharlie spawns on earth.
** <b>event0402</b>\n\nCharlie moves in to first house, second floor.
* scenario5
** <b>event0501</b>\n\nCharlie moves from first house to second house, fourth floor, keeps contract with first house.
** <b>event0502</b>\n\nThe first house is destroyed. Luckily, no-one lived there anymore.
* scenario6
** <b>event0601</b>\n\nBerta and Charlie become friends.
** <b>event0602</b>\n\nAnton and Charlie get one year older.
** <b>event0603</b>\n\nAnton joins Berta and Charlie's friendship.
** <b>event0604</b>\n\nAfter Anton, Berta, and Charlie celebrated a party, Anton and Charlie are not friends anymore.
** <b>event0605</b>\n\nAnton and Berta get divorced.

@endmindmap
